/*
 * arabixel.h -- Arabic for the screen: Arabixel Basic's glyphs as
 * bitmaps (arabixel_tab.c, generated by tools/gen_arabixel.py) and the
 * shaping that picks which of them a word needs (arabixel_shape.c).
 *
 * Glyphs are the same shape as ark12's: 12 rows, one value per row,
 * bit 0 leftmost, baseline under row 9. Unlike ark12's they join, so
 * gfx.c advances by exactly a glyph's width with no column between --
 * see arabixel_has().
 *
 * Arabixel Basic (c) 2024 ArabianDev, CC BY 4.0
 * (https://arabiandev.itch.io/arabixel-basic-font). The table is CC BY
 * 4.0 as a converted copy; the shaping code is MIT like the rest of the
 * project. LICENSE.txt and README.md here have the detail.
 *
 * SPDX-License-Identifier: MIT
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#define ARABIXEL_H  12

typedef struct {
    uint16_t cp;
    uint8_t  w;
    uint16_t rows[ARABIXEL_H];
} arabixel_glyph_t;

extern const unsigned arabixel_count;
extern const arabixel_glyph_t arabixel_glyphs[];

/* The glyph for cp, or NULL. */
const arabixel_glyph_t *arabixel_find(uint32_t cp);

/* Text this module handles: Arabic, and the Presentation Forms that
 * arabixel_shape() produces. A run of these is what gfx.c hands over. */
static inline bool arabixel_is_arabic(uint32_t cp)
{
    return (cp >= 0x0600 && cp <= 0x06FF) ||
           (cp >= 0xFB50 && cp <= 0xFDFF) ||
           (cp >= 0xFE70 && cp <= 0xFEFF);
}

/*
 * Shape a run in place, logical order in, visual (left to right) order
 * out, and return its new length, which is never longer:
 *
 * - combining marks (harakat, shadda, sukun, superscript alef) dropped:
 *   gfx.c draws a glyph beside the last, never over it;
 * - each letter replaced by its isolated, initial, medial or final form
 *   from its neighbours, and lam followed by an alef by one ligature;
 * - the run reversed, except that a sequence of digits keeps its order.
 *
 * The run is what gfx.c collected: Arabic codepoints and the spaces
 * between them. A codepoint this does not know (a digit, punctuation, a
 * letter outside the table) joins nothing and is kept as it is.
 */
int arabixel_shape(uint32_t *run, int n);
