#!/usr/bin/env python3
"""
gen_arabixel.py -- turn Arabixel Basic's Arabic glyphs into the C table in
components/arabixel/arabixel_tab.c.

Arabixel Basic (https://arabiandev.itch.io/arabixel-basic-font) is an 11px
pixel font drawn as outlines on a 2048/11 unit grid, so each glyph is
recovered exactly by testing the centre of every pixel cell against the
outline. The font file is committed beside the table
(components/arabixel/Arabixel_Basic.ttf), and this script is run by hand
when it changes, like gen_ark12.py.

Kept: the Arabic block (U+0600..06FF) and the two Presentation Forms
blocks, which hold the joined shapes -- initial, medial, final, isolated
and the lam-alef ligatures. The font has no GSUB, so choosing among those
is arabixel_shape()'s job, not the font's. Left out: the combining marks
(U+064B..065F, U+0670), which arabixel_shape() drops because gfx.c has no
way to draw one over the letter before it, and the font's ASCII, which
ark12 draws.

Rows. ark12 is 12 rows with its baseline under row 9. Arabixel letters
stand on font row y=1, so they are mapped row = 9 - y: a letter's foot
on ark12's last row above the baseline, rows y=9..-2 kept. Eight glyphs
reach y=-3 (hamza below, the jeem family's final tails) and two y=10
(lam-alef with madda or hamza above). Each loses one row so it fits:
an empty row nearest the overflow when there is one -- the gap between
a letter and its hamza, or between lam-alef and its madda -- else the
row named in SQUEEZE, a repeated stroke of a tail. Nothing is clipped.

Advance. The glyph's width is the font's own advance, and gfx.c steps by
exactly that for these glyphs, with no extra column: the joins only meet
if nothing is put between them, and the advance already carries the
font's spacing on a side that does not join.

Usage:
    ./tools/gen_arabixel.py

Requires fontTools (pip install fonttools) -- only to run this, never to
build the firmware.

SPDX-License-Identifier: MIT
"""

import hashlib
import os
import sys

from fontTools.pens.pointInsidePen import PointInsidePen
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
COMP = os.path.join(HERE, "..", "components", "arabixel")
TTF = os.path.join(COMP, "Arabixel_Basic.ttf")
OUT = os.path.join(COMP, "arabixel_tab.c")

H = 12
TOP, BOT = 9, -2            # font rows kept, row = TOP - y
RANGES = ((0x0600, 0x06FF), (0xFB50, 0xFDFF), (0xFE70, 0xFEFF))
MARKS = set(range(0x064B, 0x0660)) | {0x0670}

# A row to remove from a glyph that has no empty row to give up: the
# second of two rows of the same vertical stroke in a final jeem, hah or
# khah's tail.
SQUEEZE = {0xFE9E: -2, 0xFEA2: -2, 0xFEA6: -2}


def raster(gs, name, w, unit):
    rows = {}
    for y in range(12, -8, -1):
        for x in range(w):
            pen = PointInsidePen(gs, ((x + 0.5) * unit, (y - 0.5) * unit))
            gs[name].draw(pen)
            if pen.getResult():
                rows[y] = rows.get(y, 0) | (1 << x)
    return rows


def fit(cp, rows):
    """Remove rows until the glyph spans TOP..BOT; return {y: bits}."""
    if not rows:
        return rows
    # bits[k] is font row top - k
    top = max(rows)
    bits = [rows.get(y, 0) for y in range(top, min(rows) - 1, -1)]
    y_of = lambda k: top - k

    while top > TOP:
        # the empty row nearest the top: what is above it moves down
        k = next((k for k in range(len(bits)) if bits[k] == 0 and y_of(k) > 0), None)
        if k is None:
            sys.exit(f"U+{cp:04X}: too tall and no empty row to remove")
        del bits[k]
        top -= 1
    while y_of(len(bits) - 1) < BOT:
        # the empty row nearest the bottom: what is below it moves up
        k = next((k for k in range(len(bits) - 1, -1, -1) if bits[k] == 0 and y_of(k) <= 0), None)
        if k is None and cp in SQUEEZE:
            k = top - SQUEEZE.pop(cp)
        if k is None:
            sys.exit(f"U+{cp:04X}: too deep and no row to remove")
        del bits[k]
    return {y_of(k): b for k, b in enumerate(bits) if b}


def main():
    font = TTFont(TTF)
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    unit = font["head"].unitsPerEm / 11

    glyphs = []
    for cp in sorted(cmap):
        if not any(lo <= cp <= hi for lo, hi in RANGES) or cp in MARKS:
            continue
        name = cmap[cp]
        w = round(hmtx[name][0] / unit)
        if w <= 0 or w > 16:
            continue
        rows = fit(cp, raster(gs, name, w, unit))
        out = [rows.get(TOP - r, 0) for r in range(H)]
        glyphs.append((cp, w, out))
    if SQUEEZE:
        sys.exit(f"SQUEEZE entries not used: {SQUEEZE}")

    digest = hashlib.sha256(open(TTF, "rb").read()).hexdigest()
    o = []
    o.append("/*")
    o.append(" * arabixel_tab.c -- GENERATED by tools/gen_arabixel.py; do not edit.")
    o.append(" *")
    o.append(" * Arabixel Basic (https://arabiandev.itch.io/arabixel-basic-font)")
    o.append(" * (c) 2024 ArabianDev, licensed under CC BY 4.0. Converted to bitmaps;")
    o.append(" * ten glyphs had one row removed to fit 12 rows (see the generator).")
    o.append(f" * From Arabixel_Basic.ttf, sha256 {digest}.")
    o.append(" *")
    o.append(" * SPDX-License-Identifier: CC-BY-4.0")
    o.append(" */")
    o.append('#include "arabixel.h"')
    o.append("")
    o.append(f"const unsigned arabixel_count = {len(glyphs)};")
    o.append("")
    o.append("const arabixel_glyph_t arabixel_glyphs[] = {")
    for cp, w, rows in glyphs:
        r = ", ".join(f"0x{v:03X}" for v in rows)
        o.append(f"    {{ 0x{cp:04X}, {w:2d}, {{ {r} }} }},")
    o.append("};")
    open(OUT, "w").write("\n".join(o) + "\n")
    print(f"{len(glyphs)} glyphs -> {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
